# Generated by Django 3.2.15 on 2022-09-07 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(blank='true', max_length=100)),
                ('add', models.CharField(blank='true', max_length=100)),
                ('email', models.CharField(blank='true', max_length=100)),
            ],
        ),
    ]
