# Generated by Django 3.2.15 on 2022-08-27 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_contactus_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='email',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contactus',
            name='number',
            field=models.IntegerField(max_length=10),
        ),
    ]
