# Generated by Django 3.2.15 on 2022-08-27 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20220827_0737'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactus',
            old_name='username',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='contactus',
            old_name='password',
            new_name='number',
        ),
        migrations.AddField(
            model_name='contactus',
            name='email',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
