# Generated by Django 3.2.15 on 2022-08-27 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20220827_0759'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactus',
            name='email',
        ),
    ]
