# Generated by Django 3.2.15 on 2022-08-27 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_contactus_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactus',
            name='email',
        ),
    ]
