# Generated by Django 3.2.15 on 2022-08-27 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0013_alter_contactus_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='age',
            field=models.IntegerField(default=None),
        ),
    ]
