# Generated by Django 3.2.15 on 2022-08-27 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0014_contactus_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='age',
            field=models.IntegerField(),
        ),
    ]
