# Generated by Django 3.2.15 on 2022-08-27 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0015_alter_contactus_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactus',
            name='age',
        ),
    ]
