# Generated by Django 3.2.15 on 2022-08-27 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0019_auto_20220827_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='Password',
            field=models.CharField(default=None, max_length=122),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='address',
            field=models.CharField(default=None, max_length=122),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='c_pass',
            field=models.CharField(default=None, max_length=122),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='district',
            field=models.CharField(default=None, max_length=122),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='name',
            field=models.CharField(default=None, max_length=22),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='number',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='state',
            field=models.CharField(default=None, max_length=122),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='village',
            field=models.CharField(default=None, max_length=122),
        ),
    ]
