# Generated by Django 3.2.15 on 2022-08-29 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0021_auto_20220829_0554'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactus',
            old_name='Password',
            new_name='age',
        ),
        migrations.RenameField(
            model_name='contactus',
            old_name='address',
            new_name='email',
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='c_pass',
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='district',
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='state',
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='village',
        ),
    ]
