# Generated by Django 3.2.15 on 2022-08-29 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0024_alter_contactus_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='number',
            field=models.IntegerField(default=None),
        ),
    ]
