# Generated by Django 3.2.15 on 2022-09-02 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adhar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adhar_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Departmant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_id', models.IntegerField()),
                ('dept_Name', models.CharField(max_length=122)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_Name', models.CharField(max_length=100)),
                ('domain', models.CharField(max_length=100)),
                ('joining_Date', models.DateField()),
                ('adhar', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app_emp.adhar')),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_emp.departmant')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_Name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('employee', models.ManyToManyField(to='app_emp.Employee')),
            ],
        ),
    ]
